# Generated by Django 3.1.7 on 2021-03-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankScrewsIndexValuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('url', models.CharField(max_length=100, verbose_name='网址')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('pub_date', models.DateTimeField(verbose_name='Time')),
            ],
            options={
                'verbose_name_plural': '爬虫银行螺丝钉',
            },
        ),
    ]
